title: Be Transparent, Do The Right Thing!
email: b.trans.parent@protonmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Here you can find translations of several articles and statements regarding the current bulgarian government and it's crimes. enough. protest. ostavka.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: btransparent1
github_username:  btransparent

# Build settings
theme: minima
#theme: jekyll-theme-minimal

plugins:
  - jekyll-feed
    #minima:
    #skin: dark

